#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${PATH_TO_PHOTOS}:/usr/src/app/upload
      - ${PATH_TO_EXT_LIB}:/usr/src/app/ext_lib
      - /etc/localtime:/etc/localtime:ro
    environment:
      DB_PASSWORD: password
      DB_USERNAME: psql_user
      DB_DATABASE_NAME: immich
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - immich-model-cache:/cache
    restart: always

  redis:
    container_name: immich_redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:84882e87b54734154586e5f8abd4dce69fe7311315e2fc6d67c29614c8de2672
    ports:
      - 6379:6379
    restart: always
  
  database:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: psql_user
      POSTGRES_DB: immich
    volumes:
      - immich-db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always

volumes:
  immich-model-cache:
  immich-db-data: