---
services:
  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - ${PATH_TO_CONFIG}:/config
      - ${PATH_TO_DOWNLOADS}:/downloads
    ports:
      - ${WEBUI_PORT}:8112
      - ${TORRENTING_PORT}:6881
      - ${TORRENTING_PORT}:6881/udp
    restart: unless-stopped