---
version: "3.8"
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - radarr_config:/config
      - ${PATH_TO_MOVIES}:/movies # Path to your Plex movies folder
      - ${PATH_TO_DOWNLOADS}:/downloads # Path to your qBittorrent downloads folder
    ports:
      - 7878:7878
    restart: unless-stopped
  
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - sonarr_config:/config
      - ${PATH_TO_TV}:/tv # Path to your Plex TV Shows folder
      - ${PATH_TO_DOWNLOADS}:/downloads # Path to your qBittorrent downloads folder
    ports:
      - 8989:8989
    restart: unless-stopped
  
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - prowlarr_config:/config
    ports:
      - 9696:9696
    restart: unless-stopped
  
  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=${TZ}
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped
  
  recyclarr:
    image: ghcr.io/recyclarr/recyclarr
    container_name: recyclarr
    user: 1000:1000
    volumes:
      - recyclarr_config:/config
    environment:
      - TZ=${TZ}
  
  maintainerr:
    image: jorenn92/maintainerr:latest
    container_name: maintainerr
    volumes:
      - maintainerr_data:/opt/data
    environment:
      - TZ=${TZ}
    ports:
      - 8154:80
    restart: unless-stopped
  
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - bazarr_config:/config
      - ${PATH_TO_MOVIES}:/movies #optional
      - ${PATH_TO_TV}:/tv #optional
    ports:
      - 6767:6767
    restart: unless-stopped

networks:
  mediaserver:
    name: mediaserver
    external: true