version: "3.7"

services:
  qbittorrent:
    container_name: qbittorrent
    image: cr.hotio.dev/hotio/qbittorrent
    ports:
      - "9090:8080"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=${TZ}
    volumes:
      - qbittorrent-config:/config
      - "${PATH_TO_DOWNLOADS}:/downloads"
      - "${PATH_TO_TORRENTS}:/torrents"

volumes:
  qbittorrent-config: