---

services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_CLAIM}
    volumes:
      - plex-config:/config
      - ${PATH_TO_TV_FOLDER}:/tv
      - ${PATH_TO_MOVIES_FOLDER}:/movies
    restart: unless-stopped
    devices:
      - '/dev/dri:/dev/dri'

volumes:
  plex-config: