---

services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ={{ TIMEZONE }}
      - VERSION=docker
      - PLEX_CLAIM={{ CLAIM_TOKEN}}
    volumes:
      - plex-config:/config
      - {{ PATH_TO_TV }}:/tv
      - {{ PATH_TO_MOVIES }}:/movies
    restart: unless-stopped
    devices:
      - '/dev/dri:/dev/dri'

volumes:
  alex-config: