version: '3.8'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ${PATH_TO_DATA}:/data
      - ${PATH_TO_LETSENCRYPT}:/etc/letsencrypt