version: "3.4"
services:
  tdarr-node:
    container_name: tdarr-cpu-node
    image: ghcr.io/haveagitgat/tdarr_node:latest
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - UMASK_SET=002
      - nodeName=${NODE_NAME}
      - serverIP=${SERVER_IP}
      - serverPort=8266
      - inContainer=true
      - ffmpegVersion=6

    volumes:
      - tdarr-worker-config:/app/configs
      - tdarr-worker-logs:/app/logs
      - ${LIBRARY_PATH}:/media
      - ${TRANSCODE_CACHE_PATH}:/temp
        
volumes:
  tdarr-worker-config:
  tdarr-worker-logs: