version: "3.4"
services:
  tdarr:
    container_name: tdarr
    image: ghcr.io/haveagitgat/tdarr:latest
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 8265:8265 # webUI port
      - 8266:8266 # server port
    environment:
      - TZ=${TZ}
      - UMASK_SET=002
      - serverIP=${SERVER_IP}
      - serverPort=8266
      - webUIPort=8265
      - internalNode=true
      - inContainer=true
      - ffmpegVersion=6
      - nodeName=${NODE_NAME}
    volumes:
      - tdarr-server:/app/server
      - tdarr-config:/app/configs
      - tdarr-logs:/app/logs
      - ${LIBRARY_PATH}:/media
      - ${TRANSCODE_CACHE_PATH}:/temp

volumes:
  tdarr-server:
  tdarr-config:
  tdarr-logs:

