#
# This stack will deploy an Immich node, ie. a microservices only node that can be used in a distributed architecture to scale the Immich jobs.
# Ref: https://github.com/immich-app/immich/releases/tag/v1.106.1 see section Split Workers
# 

name: immich

services:
  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${PATH_TO_PHOTOS}:/usr/src/app/upload
      - ${PATH_TO_EXT_LIB}:/usr/src/app/ext_lib
      - /etc/localtime:/etc/localtime:ro
    environment:
      DB_PASSWORD: password
      DB_USERNAME: psql_user
      DB_URL: ${POSTRES_HOST}
      DB_DATABASE_NAME: immich
      REDIS_HOSTNAME: ${REDIS_HOST}
      IMMICH_WORKERS_EXCLUDE: 'api'
    restart: always

volumes:
  immich-model-cache:
  immich-db-data: